### ISSUE TITLE
Enable Linear Advance cannot be set in an extruder profile

### ISSUE THREAD

**Issue by x40-Community** [fieldOfView/Cura-LinearAdvanceSettingPlugin#42]
Hello,
I installed Ultimaker Cura 5.0.0 and the Linear Advance Settings plugin version 3.6.0.

I entered the following into the material file:
       <cura:setting key="material_linear_advance_factor">1.43</cura:setting>

I entered the following into the intent profile:
material_linear_advance_enable = True

When I call up the corresponding profile in Cura (after Cura restart), Linear Advance is always deactivated. When activated, the values are visible.

Even if I put material_linear_advance_factor in the intent profile it doesn't work.

You always have to activate Linear Advance manually.
Bug or am I doing something wrong?

**Comment by qwertymodo** [comment]
This bug still seems to be present in 5.1.0.  Also, the "Enable Linear Advance" option does not show up under the "Select settings" dialog, so there is no way to assign the enabled option to the material profile within the GUI.

Edit: I just realized after posting that I'm referring to a function of the Materials Settings plugin, which may or may not be related, but is at least worth mentioning here.

**Comment by qwertymodo** [comment]
Something interesting I noted looking into this which may be relevant, or may just be nothing, but it does work to save the enabled setting into a new quality profile, and when doing so, the key name is material_linear_advance_enable where most enable/disable settings use _enabled (with a 'd' on the end).

**Comment by qwertymodo** [comment]
I found a workaround.  Inside the plugin install directory (on Windows it's %APPDATA%\cura\(version)\plugins\LinearAdvanceSettingPlugin\LinearAdvanceSettingPlugin), edit linear_advance_35.def.json and linear_advance47.def.json.  Near the top, under "material_linear_advance_enable", set "default_value" to true.  Because the default K-factor for materials you haven't set is 0, enabling LA by default with a default K-value of 0 is the same as disabling it, so this is an acceptable workaround for me until the plugin can be fixed properly.

**Comment by nelsongraca** [comment]
@qwertymodo I do not see that option in v3.6.0, and yet it does not show up on cura 5.x

**Comment by fieldOfView** [comment]
Sorry, it took me a while to figure out what the actual issue was. I think I have fixed this for the next release of the plugin. Could you help test this?
https://github.com/fieldOfView/Cura-LinearAdvanceSettingPlugin/releases/tag/v3.6.1-DEV
Download the .curapackage for your version of Cura, and drop it onto the buildplate in Cura as if you were opening a 3d model.

**Comment by nelsongraca** [comment]
@fieldOfView Can confirm it's working, thank you.

**Comment by qwertymodo** [comment]
Looks like that worked!  Thanks for looking into it.

![enable_linear_advance](https://user-images.githubusercontent.com/5988870/226436347-20908316-d791-4922-baed-f0f6936fdea9.png)
